# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i @top-gg/sdk
    - run: npm i array-sort
    - run: npm i ascii-art
    - run: npm i async-limiter
    - run: npm i colors
    - run: npm i common-tags
    - run: npm i dblapi.js
    - run: npm i discord.js
    - run: npm i express
    - run: npm i ffmpeg
    - run: npm i figlet
    - run: npm i lodash
    - run: npm i lodash.set
    - run: npm i lodash.unset
    - run: npm i long
    - run: npm i ms
    - run: npm i parse-ms
    - run: npm i prism-media
    - run: npm i quick.db
    - run: npm i safe-buffer
    - run: npm i simple-youtube-api
    - run: npm i sqlite3
    - run: npm i sqlite
    - run: npm i better-sqlite
    - run: npm i snekfetch
    - run: npm i superagent
    - run: npm i table
    - run: npm i tweetnacl
    - run: npm i weather-js
    - run: npm i ws
    - run: npm i ytdl-core
